rp-rs/rp2040-project-template

Cargo.toml
When installing probe run using
`cargo install --git https://github.com/rp-rs/probe-run --branch main`
as suggested by README.md, one currently gets version 0.2.4, which uses
defmt 0.2.
So, when following the README.md, one gets the following error message:
```
Error: defmt version mismatch: firmware is using 0.1, `probe-run` supports 0.2
suggestion: `cargo install` a different non-git version of `probe-run` that supports defmt 0.1
```
This can be fixed by updating the template to defmt 0.2.
=> Upgrade dependency on defmt to 0.2.0

.cargo/config, Cargo.toml, README.md
With probe-run switching to defmt-0.3.0, the project template should be updated  accordingly, to avoid error messages:
```
Error: defmt wire format version mismatch: firmware is using 0.2, `probe-run` supports 3
suggestion: `cargo install` a different version of `probe-run` that supports defmt 3
```
~~For now, this is only a draft and should not yet be merged, as the template points to probe-run-rp, which has not yet been upgraded to defmt-0.3.0.~~
=> Upgrade to defmt-0.3.0 & refer to upstream version of probe-run

.cargo/config, Cargo.toml, memory.x, src/main.rs
The template is currently based around the HAL directly.
BSP's help remove a bunch of boilerplate that never changes (configuring boot2, providing xtal freq, etc), and are generally more newbie-friendly - we should encourage ourselves and others to use them instead!
This PR sets the BSP to Pico, with a few commented lines on how to switch this to the pro_micro_rp2040.
Do not merge this until the boot2 changes are merged into the BSPs (https://github.com/rp-rs/rp-hal/pull/153)
Resolves #9.
=> Use pico bsp

.cargo/config.toml, .vscode/settings.json, README.md
In `README.md`, elf2uf2-rs has been misspelled as elf2usb2-rs in installation commands. In `.cargo/config.toml`, a quotation mark need to be added.
For users who use VS Code with Rust Analyzer, setting target architecture could help them to avoid warning like no tests module.
=> typo: fix misspelled elf2uf2-rs

.cargo/config.toml
This is for discussion: Since changing to defmt 0.3.0, most of the time I run a new firmware for the first time, I forget to set DEFMT_LOG. And during development, I usually want more logging than the default. So I wonder if it would be good to set this by default on rp2040-project-template.
Pro:
- it's usually a better choice when starting a new project
- easier for new users (avoids questions like "why doesn't `info!(...)` work?")
Con:
- quite invisible, so new users don't learn about DEFMT_LOG
=> Set DEFMT_LOG to "debug" from .cargo/config.toml

README.md
The README.md for rp2040-hal had significantly better quality and layout.
I've borrowed those plus added some details sections to allow the page to collapse.
Also borrowed info on using elf2uf2-rs from rp2040-hal README.md
This addresses some of #16
=> Improve layout + formatting of readme + runner info

Cargo.toml
Update to latest Rust edition. This removes the requirement for resolver = "2" as this is the default.
Remove authors tag (not necessary + certain to be wrong after cloning the template).
Remove readme tag - cargo publish will automatically detect a README.md in the root of the package.
=> Cargo toml updates

.cargo/config.toml, Embed.toml, README.md, src/main.rs
We previously only had probe-run as a debug configuration.
Now that cargo embed supports defmt, gdb and a bunch of other stuff we should document that as well.
Need to use a git version, since the latest release does not support rp2040
=> Add cargo embed config + docs

README.md
Now that cargo-embed 0.13.0 is released we don't have to install a git version :tada:
=> Update docs to use cargo-embed 0.13.0

README.md
https://github.com/probe-rs/cargo-embed says:
> cargo-embed has moved repository
> 
> cargo-embed is now part of the main probe-rs repository at https://github.com/probe-rs/probe-rs.
> 
> This repository is not used anymore.
=> Update the links to cargo-embed

debug_probes.md
Also include links to source repositories of firmware files
@9names: Can you verify that I included the correct source repository for the [rust-dap-pico-ramexec-setclock.uf2](https://raw.githubusercontent.com/9names/binary-bits/main/rust-dap-pico-ramexec-setclock.uf2) firmware?
Closes #44
=> Update reference to latest picoprobe firmware

README.md
closes #57
This avoids an issue that defmt and probe run are having at the moment, but, as @jannic said in #57, this is useful regardless of that issue.
=> Update cargo embed install snippet to inclue "--locked"

Cargo.toml, README.md
With probe-run 0.3.9, there's no longer a need to revert to older versions of probe-run and defmt to work around bugs.
=> Remove temporary workarounds for probe-run/defmt issues

README.md
When not using rp-pico but rp2040_boot2 the bootloader needs to be  added. This is not obvious so added a section about it to the readme.
=> Added section for note about rp2040_boot2

.cargo/config.toml, .vscode/launch.json, README.md
The latest version of probe-rs moved all of the tools behind a single crate - update instructions to use this.
Also updated probe-rs-debugger instructions, since you can now install the plugin through the regular extensions marketplace instead of having to manually install.
Lastly, removed a stray `</details>` tag - not sure when that got introduced
=> Update probe-rs tools to 0.19

.cargo/config.toml, README.md
`probe-run` was recently announced as deprecated in favor of `probe-rs`. This changes the default runner to `probe-rs run` and removes reference to the old `probe-run`.
=> Change default runner to `probe-rs` and deprecate `probe-run`

README.md
=> Add a section about feature flags to README.md

Cargo.toml, cargo-generate/Cargo.toml, src/main.rs
https://github.com/rp-rs/rp2040-project-template/pull/75 Switched rp-pico to v0.9 which adds support for embedded-hal 1.0.0 but did not updated embedded-hal it self. This pr updates embedded-hal
=> Switch to embedded_hal 1.0.0

.cargo/config.toml
It doesn't work anyway, see https://github.com/rust-lang/rust/pull/124712
=> Remove -C inline-threshold=5 option from config.toml

README.md
Update the feature flags line to have the same version as used in the `Cargo.toml` file.
This makes it more seamless for users to copy-paste this feature flag line and use the latest version.
=> Update README sample code version to match actual used

cargo-generate/launch.json, cargo-generate/remove_rprs.rhai
The `.vscode/launch.json` file has a hard-coded path to the `programBinary`, which does not work if you create a project with a different name using `cargo generate rp-rs/rp2040-project-template`.
https://github.com/rp-rs/rp2040-project-template/blob/4cfa8a7d7b2991f77d85199b9d65296d54ced071/.vscode/launch.json#L27
This PR replaces that file with a generated `.vscode/launch.json` file, with the correct path to the `programBinary`. The rest of the file is unchanged.
=> Fix project name in generated launch.json

.vscode/settings.json
https://github.com/rust-lang/rust-analyzer/pull/13799
=> Update settings.json to use new rust-analyzer.check.allTargets

cargo-generate.toml
Creating a project using this template and  `cargo-generate@0.23.0` causes the following error which prevents the project from being created:
```
🤷   Project Name: test-rs
🔧   Destination: /tmp/test-rs ...
🔧   project-name: test-rs ...
🔧   Generating template ...
✔ 🤷   Which flashing method do you intend to use? · probe-rs
[ 1/17]   Done: .cargo/config.toml
[ 2/17]   Done: .cargo
[ 4/17]   Done: .github/workflows
[ 5/17]   Done: .github
[ 6/17]   Done: .gitignore
[ 7/17]   Done: .vscode/launch.json
[ 8/17]   Done: .vscode/settings.json
[ 9/17]   Done: .vscode
[10/17]   Done: APACHE2.0
[11/17]   Done: Cargo.toml
[12/17]   Done: Embed.toml
[13/17]   Done: MIT
[14/17]   Done: build.rs
[15/17]   Done: memory.x
[16/17]   Done: src/main.rs
[17/17]   Done: src
Error: Substitution skipped, found …
```
=> Fix for cargo-generate@0.23.0 failing to create project from template

cargo-generate/launch.json
The comment after `consoleLogLevel` in `launch.json` implies you could set this value to `Trace`, which is incorrect.
See
https://github.com/probe-rs/vscode/blob/efeb1c5a737bc93ecd3a3503e905548b73e74b3c/package.json#L135-L149
=> Fix incorrect options in comment

README.md
The links to the probe-rs site in the README use a trailing slash which breaks them (at least in Firefox), this just removes the slash.
=> Fix probe-rs README links

cargo-generate/config.toml
This change mirros 8f7b4b67.
When fetching through cargo-generate, a different file is used to build the config file.
Fixes #97
=> fix: remove inline-threshold from the config's template too

.cargo/config.toml, cargo-generate/config.toml
Since rust v1.74, the linker can be selected without using rustflags. This plays nicer with `RUSTFLAGS`.
Fixes #82
=> fix: Update cargo's config to use the new linker parameter

README.md
This is an attempt at clarifying the possible confusion reported by @moritztim.
Fixes #90
=> doc: Document the project creation process

Cargo.toml, src/main.rs
See https://github.com/rp-rs/rp235x-project-template/pull/5 for more context.
Currently, this repository specifies edition 2021 in `Cargo.toml`, but it seems `cargo generate` generates a crate with the default edition of the toolchain. This means an ordinary user would use edition 2024 for a fresh project. So, I think it's a good idea to test edition 2024 instead of 2021 for testing on GitHub Actions CI.
=> Use edition 2024

README.md, cargo-generate.toml, cargo-generate/config.toml
This replaces usage of elf2uf2-rs with picotool, in line with [rp-hal PR 947](https://github.com/rp-rs/rp-hal/pull/947). I've tested the updated template and successfully flashed the firmware using picotool to a RP Pico.
A second commit tidies up code blocks in the readme to replace a language tag of `console` with a leading `$` to just language `sh`.
=> Switch from elf2uf2-rs to picotool
